name: Swift

on:
  push:
    branches: [ 3.0.0-beta.1 ]
  pull_request:
    branches: [ 3.0.0-beta.1 ]

jobs:
  build-ios:
    name: Test on iOS 15
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    runs-on: macOS-11
    strategy:
      matrix:
        destination: ['OS=15.2,name=iPhone 13 Pro']
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild test -destination '${{ matrix.destination }}' -scheme 'SwiftExtensions-Package'
    - name: Run tests
      run: xcodebuild test -destination '${{ matrix.destination }}' -scheme 'SwiftExtensions-Package'

